function [H, G]=HG(I)

syms p q r u v w phi theta Psi X Y Z
syms u1 u2 u3 u4 Ix Iy Iz Ixz c_l c_d

% p=x(1);
% q=x(2);
% r=x(3);
% u=x(4);
% v=x(5);
% w=x(6);
% phi=x(7);
% theta=x(8);
% psi=x(9);
% X=x(10);
% Y=x(11);
% Z=x(12);
% 
% u1=U(1);
% u2=U(2);
% u3=U(3);
% u4=U(4);

Ix=I(1,1); Iy=I(2,2); Iz=I(3,3); Ixz=0;

%I=@(Ix, Iy, Iz, Ixz)[Ix, 0, Ixz;0, Iy, 0; Ixz, 0, Iz];

Rot=@(phi, Psi, theta)(1/cos(theta))*[cos(theta), sin(theta)*sin(phi), sin(theta)*cos(phi);...
    0,cos(theta)*cos(phi), -cos(theta)*sin(phi);...
    0,sin(phi), cos(phi)];
T=@(phi, Psi, theta)[1,0,0;...
    0,cos(phi), sin(phi);...
    0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
    0,1,0;...
    sin(theta), 0,cos(theta)]*[cos(Psi), sin(Psi), 0;...
    -sin(Psi), cos(Psi), 0; ...
    0,0,1];
 
rho_inf=1.225;
g=9.8;
area=88.95;
a=4;
m=26421*.435;%6350;
% w=18.92;
% h=2.2;
% l=11.63; 
mg=m*g;

de=@(p,q,r,u,v,w,phi, theta, Psi, X, Y, Z, u1, u2, u3, u4, c_l, c_d)[inv([Ix, 0, Ixz;0, Iy, 0; Ixz, 0, Iz])*([(1-2*u3)*u1*(sin(u2))*a; u4; (1-2*u3)*u1*cos(u2)*a]-[(Iz-Iy)*q*r + Ixz*q*p;(Ix-Iz)*p*r+Ixz*(r^2-p^2);(Iy-Ix)*p*q-Ixz*q*r]);...
 (1/m)*(([1,0,0;...
    0,cos(phi), sin(phi);...
    0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
    0,1,0;...
    sin(theta), 0,cos(theta)]*[cos(Psi), sin(Psi), 0;...
    -sin(Psi), cos(Psi), 0; ...
    0,0,1])*[0,0,-.5*rho_inf*(u*u+v^2+w^2)*c_l*area]'+([1,0,0;...
    0,cos(phi), sin(phi);...
    0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
    0,1,0;...
    sin(theta), 0,cos(theta)]*[cos(Psi), sin(Psi), 0;...
    -sin(Psi), cos(Psi), 0; ...
    0,0,1])*[-.5*rho_inf*(u^2+v^2+w^2)*c_d*(.1*area), 0, 0]'+[-mg*sin(theta) + u1.*cos(u2); ...
    mg*cos(theta)*sin(phi); ...
    mg*cos(theta)*cos(phi) - u1.*sin(u2)])+[(r*v-q*w);(p*w-u*r);(u*q-p*v)];...
    
(1/cos(theta))*[cos(theta), sin(theta)*sin(phi), sin(theta)*cos(phi);...
    0,cos(theta)*cos(phi), -cos(theta)*sin(phi);...
    0,sin(phi), cos(phi)]*[p;q;r];...
    
inv([1,0,0;...
    0,cos(phi), sin(phi);...
    0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
    0,1,0;...
    sin(theta), 0,cos(theta)]*[cos(Psi), sin(Psi), 0;...
    -sin(Psi), cos(Psi), 0; ...
    0,0,1])*[u;v;w]];

% de_2=@(p,q,r,u,v,w,phi, theta, psi, X, Y, Z, u1, u2, u3, u4, c_l, c_d,Ix, Iy, Iz, Ixz ) (1/m)*(([1,0,0;...
%     0,cos(phi), sin(phi);...
%     0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
%     0,1,0;...
%     sin(theta), 0,cos(theta)]*[cos(psi), sin(psi), 0;...
%     -sin(psi), cos(psi), 0; ...
%     0,0,1])*[0,0,-.5*rho_inf*(u*u+v^2+w^2)*c_l*area]'+([1,0,0;...
%     0,cos(phi), sin(phi);...
%     0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
%     0,1,0;...
%     sin(theta), 0,cos(theta)]*[cos(psi), sin(psi), 0;...
%     -sin(psi), cos(psi), 0; ...
%     0,0,1])*[-.5*rho_inf*(u^2+v^2+w^2)*c_d*(.1*area), 0, 0]'+[-mg*sin(theta) + u1.*cos(eps); ...
%     mg*cos(theta)*sin(phi); ...
%     mg*cos(theta)*cos(phi) - u1.*sin(eps)])+[(r*v-q*w);(p*w-u*r);(u*q-p*v)];
% 
% 
% 
% de_3=@(p,q,r,u,v,w,phi, theta, psi, X, Y, Z, u1, u2, u3, u4, c_l, c_d, Ix, Iy, Iz, Ixz) (1/cos(theta))*[cos(theta), sin(theta)*sin(phi), sin(theta)*cos(phi);...
%     0,cos(theta)*cos(phi), -cos(theta)*sin(phi);...
%     0,sin(phi), cos(phi)]*[p;q;r];
% 
% de_4=@(p,q,r,u,v,w,phi, theta, psi, X, Y, Z, u1, u2, u3, u4, c_l, c_d,Ix, Iy, Iz, Ixz ) inv([1,0,0;...
%     0,cos(phi), sin(phi);...
%     0,-sin(phi), cos(phi)]*[cos(theta), 0, -sin(theta);...
%     0,1,0;...
%     sin(theta), 0,cos(theta)]*[cos(psi), sin(psi), 0;...
%     -sin(psi), cos(psi), 0; ...
%     0,0,1])*[u;v;w];

%de=matlabFunction([de_1; de_2; de_3; de_4]);
H=matlabFunction([diff(de, p),diff(de, q),diff(de, r),diff(de, u),diff(de, v),diff(de, w),diff(de, phi),diff(de, theta),diff(de, Psi), diff(de, X),diff(de, Y),diff(de, Z)]);
G=matlabFunction([diff(de, u1), diff(de, u2),diff(de, u3),diff(de, u4)]);
end